import { Router } from 'express';
import { adminAuth } from '../middleware/adminAuth.js';
import { adminLogin, adminMe, approveAllWaitingParticipants, approveWaitingParticipant, downloadProjectFile, getEssayReviews, getMonitoring, getOverallScores, getProjectFilePreview, getProjectReviews, getWaitingParticipants, getWaitingRoomConfig, resetParticipantSessions, streamProjectFilePreview, updateEssayReview, updateProjectReview, updateWaitingRoomConfig, } from '../controllers/adminController.js';
import { createProjectTheme, createTheme, deleteProjectTheme, deleteTheme, listAdminProjectThemes, listAdminThemes, updateProjectTheme, updateTheme, } from '../controllers/themeController.js';
import { createQuestion, updateQuestion, deleteQuestion, } from '../controllers/questionController.js';
import { listProjectCases, createProjectCase, updateProjectCase, deleteProjectCase, } from '../controllers/projectCaseController.js';
const router = Router();
router.post('/admin/login', adminLogin);
router.get('/admin/me', adminAuth, adminMe);
router.post('/admin/sessions/reset', adminAuth, resetParticipantSessions);
router.get('/admin/waiting-room/config', adminAuth, getWaitingRoomConfig);
router.patch('/admin/waiting-room/config', adminAuth, updateWaitingRoomConfig);
router.get('/admin/waiting-room/participants', adminAuth, getWaitingParticipants);
router.post('/admin/waiting-room/participants/approve-all', adminAuth, approveAllWaitingParticipants);
router.post('/admin/waiting-room/participants/:participantId/approve', adminAuth, approveWaitingParticipant);
router.get('/admin/themes', adminAuth, listAdminThemes);
router.post('/admin/themes', adminAuth, createTheme);
router.patch('/admin/themes/:themeId', adminAuth, updateTheme);
router.delete('/admin/themes/:themeId', adminAuth, deleteTheme);
router.get('/admin/project-themes', adminAuth, listAdminProjectThemes);
router.post('/admin/project-themes', adminAuth, createProjectTheme);
router.patch('/admin/project-themes/:themeId', adminAuth, updateProjectTheme);
router.delete('/admin/project-themes/:themeId', adminAuth, deleteProjectTheme);
router.post('/admin/questions', adminAuth, createQuestion);
router.patch('/admin/questions/:questionId', adminAuth, updateQuestion);
router.delete('/admin/questions/:questionId', adminAuth, deleteQuestion);
router.get('/admin/project-cases', adminAuth, listProjectCases);
router.post('/admin/project-cases', adminAuth, createProjectCase);
router.patch('/admin/project-cases/:projectCaseId', adminAuth, updateProjectCase);
router.delete('/admin/project-cases/:projectCaseId', adminAuth, deleteProjectCase);
router.get('/admin/monitoring', adminAuth, getMonitoring);
router.get('/admin/essay-reviews', adminAuth, getEssayReviews);
router.patch('/admin/essay-reviews/:answerId', adminAuth, updateEssayReview);
router.get('/admin/project-reviews', adminAuth, getProjectReviews);
router.patch('/admin/project-reviews/:submissionId', adminAuth, updateProjectReview);
router.get('/admin/project-reviews/:submissionId/preview', adminAuth, getProjectFilePreview);
router.get('/admin/project-reviews/:submissionId/preview/content', adminAuth, streamProjectFilePreview);
router.get('/admin/project-reviews/:submissionId/download', adminAuth, downloadProjectFile);
router.get('/admin/overall-scores', adminAuth, getOverallScores);
export default router;
