import { Router } from 'express';
import { getConfig } from '../controllers/configController.js';
import { listProjectThemes, listThemes } from '../controllers/themeController.js';
import { listQuestionsByTheme } from '../controllers/questionController.js';
import { getProjectCaseByTheme } from '../controllers/projectCaseController.js';
import { checkParticipantResult } from '../controllers/participantResultController.js';
const router = Router();
router.get('/config', getConfig);
router.get('/themes', listThemes);
router.get('/project-themes', listProjectThemes);
router.get('/themes/:themeId/questions', listQuestionsByTheme);
router.get('/project-themes/:themeId/project-case', getProjectCaseByTheme);
router.get('/participant-results/:participantNumber', checkParticipantResult);
export default router;
